# Generated by Django 5.2.1 on 2025-05-25 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genre",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
