# Generated by Django 5.2.1 on 2025-05-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_book_is_available_alter_book_genre_rentbooks"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rentbooks",
            old_name="user",
            new_name="reader",
        ),
    ]
