# Generated by Django 5.2.1 on 2025-05-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_rename_user_rentbooks_reader"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentbooks",
            name="return_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата возврата книги"),
        ),
    ]
