# Generated by Django 5.2.1 on 2025-05-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_alter_rentbooks_return_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="available_quantity",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Доступное количество книг"),
            preserve_default=False,
        ),
    ]
