# Generated by Django 5.2.1 on 2025-05-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_book_available_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rentbooks",
            name="term",
        ),
        migrations.AddField(
            model_name="rentbooks",
            name="deadline",
            field=models.DateField(
                default="2025-05-31",
                help_text="Укажите крайний срок сдачи книги в формате YYYY-MM-DD",
                verbose_name="Крайний срок сдачи книги",
            ),
            preserve_default=False,
        ),
    ]
