# Generated by Django 5.2.1 on 2025-05-31 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_remove_rentbooks_term_rentbooks_deadline"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rentbooks",
            old_name="reader",
            new_name="user",
        ),
    ]
